// SPDX-License-Identifier: GPL-3.0-or-later
//! Pointing GTK at the session's color scheme.
//!
//! `appearance.palette` reaches the wlRIX components through their own config files and the C#
//! applications through `com.wlrix.Settings` directly. GTK reads neither. What it does read is
//! `$XDG_CONFIG_HOME/gtk-3.0/gtk.css` and its GTK 4 twin, which is what these are written to.
//!
//! ## A GTK application takes the scheme when it starts, and not again
//!
//! **GTK does not reload `gtk.css` when it changes.** Measured, not assumed: a GTK 3 window left
//! running across a `Set` reported the same headerbar color ten seconds later. So a scheme change
//! reaches every GTK application started *after* it, and the ones already open keep what they
//! had until they are restarted. The compositor, the desktop, the tray and the C# applications
//! all change immediately; GTK is the one that lags, and it is worth knowing which.
//!
//! There are two ways to close that gap and neither is a stylesheet. KDE injects a GTK 3 module
//! (`colorreload-gtk-module`, which is why it appears in the reference `settings.ini` under
//! `_docs/kde-config-ref`) that listens on D-Bus and reloads the provider from inside each
//! application; GTK 4 dropped module support, so the other half of the answer is
//! `org.freedesktop.impl.portal.Settings`. Both are their own piece of work.
//!
//! ## What this writes, and what it does not
//!
//! Two `@import` lines. The stylesheets they name are installed with `wlrix-assets` and the
//! per-scheme half of them is generated by `wlrix-compositor --dump-gtk-theme` out of the window
//! frame's own drawing code. This daemon has no `wlrix-ui` dependency and knows a scheme only as
//! a string, which is exactly why it names a file rather than emitting any color itself.
//!
//! `gtk-theme-name` is deliberately **not** set. libadwaita ignores it, and `share/themes/wlRIX`
//! is a stylesheet directory rather than a complete GTK theme -- the widgets keep Adwaita's
//! shape and only take wlRIX's colors. Claiming the name would promise a theme that is not
//! there.
//!
//! ## The file is not ours
//!
//! `gtk.css` is one file with no `conf.d` beside it, so it has to be touched -- but somebody may
//! well have their own rules in it. The wlRIX lines go in a **marked block**, and everything
//! outside that block survives untouched, which is the same promise [`crate::edit`] makes for
//! TOML. The block goes at the top because CSS requires `@import` to precede other rules.

use std::path::{Path, PathBuf};

/// Opens the region of `gtk.css` this daemon owns.
const BEGIN: &str = "/* >>> wlRIX: written by wlrix-settings-daemon. Edits here are replaced. */";
/// Closes it.
const END: &str = "/* <<< wlRIX */";

/// Where IRIX put the window buttons: the menu on the left, minimize and maximize on the right,
/// and no close button at all -- Close lives in the window menu, which is what the menu button
/// opens. `wlrix-compositor`'s own frame has exactly these three.
const DECORATION_LAYOUT: &str = "menu:minimize,maximize";

/// The GTK generations to write for.
const GENERATIONS: &[&str] = &["gtk-3.0", "gtk-4.0"];

/// Point GTK at `scheme`.
///
/// Never fails loudly: a scheme was written to the wlRIX config files whatever happens here, and
/// a GTK stylesheet that could not be updated is worth a log line rather than a failed `Set`.
/// The caller has already committed.
pub fn apply(config_home: &Path, scheme: &str) {
    let Some(theme) = theme_root() else {
        tracing::debug!(
            "no wlRIX GTK stylesheets on XDG_DATA_DIRS; not pointing GTK at {scheme}. \
             Install wlrix-assets to get them."
        );
        return;
    };

    for generation in GENERATIONS {
        let dir = config_home.join(generation);
        if let Err(err) = write_generation(&dir, &theme, generation, scheme) {
            tracing::warn!("could not point {generation} at {scheme}: {err}");
        }
    }
    tracing::info!("pointed GTK at {scheme}");
}

fn write_generation(
    dir: &Path,
    theme: &Path,
    generation: &str,
    scheme: &str,
) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;

    let css = dir.join("gtk.css");
    let existing = read_or_empty(&css)?;
    let updated = merge_block(&existing, &import_block(theme, generation, scheme));
    write_if_changed(&css, &existing, &updated)?;

    // Scheme-independent, so this is idempotent after the first run -- but done here anyway
    // rather than once at install time, because it belongs to a user's config directory and
    // there is no install step that owns one.
    //
    // The layout here is a *fallback*, and worth being precise about after an earlier guess got
    // it wrong. Measured on Wayland: GTK 3 ignores `gtk-decoration-layout` in this file
    // entirely, keeping its own `menu:close`, and reads the Settings portal instead -- but only
    // when `GTK_USE_PORTAL=1`, which `start-wlrix.sh` now exports. GTK 4 reads the portal
    // either way. So the real answer is `xdg-desktop-portal-wlrix`'s Settings backend; this
    // line is what an XWayland GTK 3 application and a session with no portal still read.
    let ini = dir.join("settings.ini");
    let existing = read_or_empty(&ini)?;
    let updated = set_ini_key(
        &existing,
        "Settings",
        "gtk-decoration-layout",
        DECORATION_LAYOUT,
    );
    write_if_changed(&ini, &existing, &updated)
}

fn read_or_empty(path: &Path) -> std::io::Result<String> {
    match std::fs::read_to_string(path) {
        Ok(text) => Ok(text),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(String::new()),
        Err(err) => Err(err),
    }
}

/// Write only when the contents moved.
///
/// GTK watches these files, and a write that changes nothing still fires the watch -- so every
/// unrelated `Set` would have every GTK application reparse its whole stylesheet.
fn write_if_changed(path: &Path, existing: &str, updated: &str) -> std::io::Result<()> {
    if existing == updated {
        return Ok(());
    }
    std::fs::write(path, updated)?;
    tracing::debug!("wrote {}", path.display());
    Ok(())
}

/// The block of wlRIX lines for one GTK generation.
///
/// Absolute `file://` URLs: a relative one would resolve against the user's config directory,
/// which is not where the stylesheets are. The scheme sheet comes second so its colors and its
/// asset URLs win over the structural sheet.
fn import_block(theme: &Path, generation: &str, scheme: &str) -> String {
    let sheet = |name: String| {
        format!(
            "@import url(\"file://{}\");",
            theme.join(generation).join(name).display()
        )
    };
    format!(
        "{BEGIN}\n{}\n{}\n{END}\n",
        sheet("wlrix.css".to_owned()),
        sheet(format!("schemes/{scheme}.css")),
    )
}

/// Replace the marked block in `existing`, or put one at the top if there is none.
///
/// At the top because CSS requires `@import` before any other rule -- a block appended to a file
/// that already had rules in it would be ignored, silently, which is the worst way for this to
/// fail.
fn merge_block(existing: &str, block: &str) -> String {
    let mut rest = match (existing.find(BEGIN), existing.find(END)) {
        (Some(start), Some(end)) if end > start => {
            let after = end + END.len();
            let mut rest = String::with_capacity(existing.len());
            rest.push_str(&existing[..start]);
            rest.push_str(existing[after..].trim_start_matches('\n'));
            rest
        }
        _ => existing.to_owned(),
    };

    // A marker with no partner: somebody edited inside the block and broke it, so there is no
    // way to tell where our region ended. Dropping the stray marker line and nothing else is the
    // smallest repair that still leaves the file with exactly one block -- without it every
    // later write would prepend another. What was inside the damaged block stays, because it
    // might be theirs by now; a stale @import is a warning on stderr, not lost work.
    if rest.contains(BEGIN) || rest.contains(END) {
        rest = rest
            .lines()
            .filter(|line| line.trim() != BEGIN && line.trim() != END)
            .collect::<Vec<_>>()
            .join("\n");
    }

    let rest = rest.trim_start_matches('\n');
    if rest.trim().is_empty() {
        block.to_owned()
    } else {
        format!("{block}\n{}\n", rest.trim_end())
    }
}

/// Set `key` under `[section]` in an INI file, leaving every other key and section alone.
///
/// A hand-rolled editor for one key in one shape of file, deliberately. `crate::edit` is
/// `toml_edit` and has nothing to say about INI; a general INI library for four lines of output
/// would be a dependency to carry for the life of the project.
fn set_ini_key(existing: &str, section: &str, key: &str, value: &str) -> String {
    let header = format!("[{section}]");
    let line = format!("{key}={value}");

    let mut out: Vec<String> = Vec::new();
    let mut in_section = false;
    let mut wrote = false;
    let mut seen_section = false;

    for text in existing.lines() {
        let trimmed = text.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            // Leaving the section: if the key was never there, add it before moving on, so it
            // lands under its own header rather than under whichever one comes next.
            if in_section && !wrote {
                out.push(line.clone());
                wrote = true;
            }
            in_section = trimmed == header;
            seen_section |= in_section;
            out.push(text.to_owned());
            continue;
        }

        // Only the key itself, and only inside the section. A commented-out one is left as the
        // comment it is.
        let is_ours = in_section
            && trimmed
                .split_once('=')
                .is_some_and(|(name, _)| name.trim() == key);
        if is_ours {
            if !wrote {
                out.push(line.clone());
                wrote = true;
            }
            continue;
        }
        out.push(text.to_owned());
    }

    if !wrote {
        if !seen_section {
            if !out.is_empty() {
                out.push(String::new());
            }
            out.push(header);
        }
        out.push(line);
    }

    let mut text = out.join("\n");
    text.push('\n');
    text
}

/// The installed stylesheet directory, found the way GTK finds a theme: by name, on the XDG data
/// directories.
///
/// Not a compiled-in `/usr/share`: the components install under `PREFIX`, and a prefix other
/// than `/usr` is a supported arrangement everywhere else in wlRIX.
fn theme_root() -> Option<PathBuf> {
    data_dirs()
        .into_iter()
        .map(|dir| dir.join("themes").join("wlRIX"))
        .find(|dir| dir.join("gtk-3.0").join("wlrix.css").is_file())
}

/// `$XDG_DATA_DIRS`, then `$XDG_DATA_HOME`, with the spec's defaults for either.
fn data_dirs() -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    if let Some(home) = std::env::var_os("XDG_DATA_HOME").filter(|v| !v.is_empty()) {
        dirs.push(PathBuf::from(home));
    } else if let Some(home) = std::env::var_os("HOME").filter(|v| !v.is_empty()) {
        dirs.push(PathBuf::from(home).join(".local").join("share"));
    }

    let system = std::env::var_os("XDG_DATA_DIRS")
        .filter(|v| !v.is_empty())
        .unwrap_or_else(|| "/usr/local/share:/usr/share".into());
    dirs.extend(std::env::split_paths(&system));
    dirs
}

#[cfg(test)]
mod tests {
    use super::*;

    fn block() -> String {
        import_block(Path::new("/usr/share/themes/wlRIX"), "gtk-3.0", "gotham")
    }

    #[test]
    fn a_fresh_file_gets_only_our_block() {
        let out = merge_block("", &block());
        assert!(out.starts_with(BEGIN));
        assert!(out.contains("schemes/gotham.css"));
        assert!(out.trim_end().ends_with(END));
    }

    #[test]
    fn somebody_elses_rules_survive() {
        // The whole point of a marked block. A user with their own font rule in gtk.css should
        // not lose it because they changed color scheme.
        let theirs = "/* mine */\nwindow { font-size: 13px; }\n";
        let out = merge_block(theirs, &block());
        assert!(out.contains("/* mine */"));
        assert!(out.contains("window { font-size: 13px; }"));
    }

    #[test]
    fn our_block_comes_first() {
        // CSS requires @import before any other rule. Appended, the imports would be ignored
        // silently -- the theme would simply never apply and nothing would say why.
        let out = merge_block("window { font-size: 13px; }\n", &block());
        assert!(out.starts_with(BEGIN), "{out}");
        assert!(out.find(BEGIN) < out.find("window {"));
    }

    #[test]
    fn switching_scheme_replaces_rather_than_repeats() {
        let first = merge_block("", &block());
        let second = merge_block(
            &first,
            &import_block(Path::new("/usr/share/themes/wlRIX"), "gtk-3.0", "classic"),
        );
        assert_eq!(second.matches(BEGIN).count(), 1, "{second}");
        assert!(second.contains("schemes/classic.css"));
        assert!(!second.contains("schemes/gotham.css"), "{second}");
    }

    #[test]
    fn rewriting_the_same_scheme_changes_nothing() {
        // What `write_if_changed` relies on. GTK watches this file, so an unstable rendering
        // would have every GTK application reparse its stylesheet on every unrelated Set.
        let once = merge_block("body { color: red; }\n", &block());
        let twice = merge_block(&once, &block());
        assert_eq!(once, twice);
    }

    #[test]
    fn a_block_somebody_broke_is_replaced_rather_than_doubled() {
        // A begin with no end: the file is not what we left, and leaving it would mean the
        // imports stayed wrong forever with nothing to say so.
        let damaged = format!("{BEGIN}\n@import url(\"file:///gone.css\");\nwindow {{}}\n");
        let out = merge_block(&damaged, &block());
        assert_eq!(out.matches(BEGIN).count(), 1, "{out}");
        assert!(out.contains("schemes/gotham.css"));
        // What was inside it stays: with no end marker there is no telling where our region
        // stopped, and guessing would delete somebody's rules.
        assert!(out.contains("window {}"), "{out}");

        // And it settles: a second pass adds nothing.
        assert_eq!(merge_block(&out, &block()), out);
    }

    #[test]
    fn an_ini_gains_the_section_it_needs() {
        let out = set_ini_key("", "Settings", "gtk-decoration-layout", DECORATION_LAYOUT);
        assert_eq!(
            out,
            format!("[Settings]\ngtk-decoration-layout={DECORATION_LAYOUT}\n")
        );
    }

    #[test]
    fn an_ini_keeps_its_other_keys() {
        let theirs = "[Settings]\ngtk-font-name=Cantarell 11\ngtk-icon-theme-name=Papirus\n";
        let out = set_ini_key(theirs, "Settings", "gtk-decoration-layout", "menu:minimize");
        assert!(out.contains("gtk-font-name=Cantarell 11"));
        assert!(out.contains("gtk-icon-theme-name=Papirus"));
        assert!(out.contains("gtk-decoration-layout=menu:minimize"));
    }

    #[test]
    fn an_existing_value_is_replaced_not_repeated() {
        let theirs = "[Settings]\ngtk-decoration-layout=icon:minimize,maximize,close\n";
        let out = set_ini_key(theirs, "Settings", "gtk-decoration-layout", "menu:maximize");
        assert_eq!(out.matches("gtk-decoration-layout").count(), 1, "{out}");
        assert!(out.contains("=menu:maximize"));
        assert!(!out.contains("close"));
    }

    #[test]
    fn a_key_of_the_same_name_in_another_section_is_left_alone() {
        // GTK's own settings.ini has one section, but nothing stops a file having more, and
        // rewriting a stranger's key because the name matched would be a real loss.
        let theirs = "[Other]\ngtk-decoration-layout=theirs\n\n[Settings]\nfoo=bar\n";
        let out = set_ini_key(theirs, "Settings", "gtk-decoration-layout", "ours");
        assert!(out.contains("gtk-decoration-layout=theirs"), "{out}");
        assert!(out.contains("gtk-decoration-layout=ours"), "{out}");
    }

    #[test]
    fn the_key_lands_under_its_own_section() {
        // Appended blindly it would end up under `[Other]`, where GTK never looks.
        let theirs = "[Settings]\nfoo=bar\n\n[Other]\nbaz=qux\n";
        let out = set_ini_key(theirs, "Settings", "gtk-decoration-layout", "ours");
        let ours = out.find("gtk-decoration-layout").expect("written");
        let other = out.find("[Other]").expect("kept");
        assert!(ours < other, "{out}");
    }

    #[test]
    fn a_commented_out_key_is_left_as_a_comment() {
        let theirs = "[Settings]\n# gtk-decoration-layout=icon:close\n";
        let out = set_ini_key(theirs, "Settings", "gtk-decoration-layout", "ours");
        assert!(out.contains("# gtk-decoration-layout=icon:close"), "{out}");
        assert!(out.contains("\ngtk-decoration-layout=ours"), "{out}");
    }

    #[test]
    fn setting_the_same_value_twice_changes_nothing() {
        let once = set_ini_key("[Settings]\nfoo=bar\n", "Settings", "k", "v");
        let twice = set_ini_key(&once, "Settings", "k", "v");
        assert_eq!(once, twice);
    }

    #[test]
    fn the_imports_are_absolute() {
        // A relative url() in gtk.css resolves against the user's config directory, which is not
        // where the stylesheets are -- and GTK reports a missing import as a parse warning on
        // stderr that nobody is reading.
        let out = block();
        for line in out.lines().filter(|l| l.starts_with("@import")) {
            assert!(line.contains("url(\"file:///"), "{line}");
        }
    }
}
